#!/usr/bin/env python3
"""
TDX local data import tool for Kronos fine-tuning.

Reads local TDX (通达信) historical K-line data and converts it to the Kronos
6-field format (open, high, low, close, vol, amt) for model fine-tuning.

Features:
- Direct import of daily (1d) and 5-min (5m) from TDX local files
- Other periods (1m, 15m, 30m, 60m, 1w, 1M) generated by resampling
- Configurable price adjustment with automatic factor fetching
- Amount formula: prefer original data, fallback to mean(OHLC) * vol
- Historical data continuity analysis with gap reporting
"""

import argparse
import os
import pickle
import sys
from collections import defaultdict
from datetime import datetime, timedelta
from typing import Optional

import numpy as np
import pandas as pd

# Add project root for tdxdata access
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from mootdx.reader import Reader
from tdxdata.sources.adjust import ADJUST_MAP, apply_adjust

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# The 6-field format used by Kronos project
FEATURE_COLUMNS = ["open", "high", "low", "close", "vol", "amt"]

# Period configuration: how to obtain each supported period
PERIOD_CONFIG = {
    "1m":   {"source": "direct", "method": "minute_1"},
    "5m":   {"source": "direct", "method": "minute_5"},
    "1d":   {"source": "direct", "method": "daily"},
    "15m":  {"source": "resample", "base": "5m",  "rule": "15min"},
    "30m":  {"source": "resample", "base": "5m",  "rule": "30min"},
    "60m":  {"source": "resample", "base": "5m",  "rule": "1h"},
    "1w":   {"source": "resample", "base": "1d",  "rule": "W-FRI"},
    "1M":   {"source": "resample", "base": "1d",  "rule": "1ME"},
}

# Default TDX data directory (wine prefix)
DEFAULT_TDXDIR = os.path.expanduser("~/.local/share/tdxcfv/drive_c/tc/")

# Resample aggregation rules
OHLCV_AGG = {
    "open": "first",
    "high": "max",
    "low": "min",
    "close": "last",
    "volume": "sum",
    "amount": "sum",
}

# TDX column mapping to Kronos 6-field format
TDX_TO_KRONOS = {
    "volume": "vol",
    "vol": "vol",
    "amount": "amt",
    "amt": "amt",
}


# ---------------------------------------------------------------------------
# Gap / continuity analysis
# ---------------------------------------------------------------------------

def check_daily_continuity(
    df: pd.DataFrame, symbol: str, min_date=None, max_date=None
) -> list[dict]:
    """
    Check daily data for missing trading days.

    A gap is defined as >= 2 consecutive weekdays without data.
    Returns list of gap records: {symbol, start, end, days_missing, pct}.
    """
    if df.empty:
        return []

    date_col = "date" if "date" in df.columns else df.index.name
    if date_col and date_col != "date":
        dates = pd.to_datetime(df.index)
    else:
        dates = pd.to_datetime(df["date"]) if "date" in df.columns else pd.to_datetime(df.index)

    dates = sorted(dates.dropna().unique())

    if len(dates) < 2:
        return []

    d0 = pd.Timestamp(min_date) if min_date else dates[0]
    d1 = pd.Timestamp(max_date) if max_date else dates[-1]

    # Build expected weekday calendar (Mon-Fri)
    expected = pd.bdate_range(start=d0, end=d1, freq="C", weekmask="Mon Tue Wed Thu Fri")
    observed = set(pd.Timestamp(d).date() for d in dates)
    expected_set = set(d.date() for d in expected)

    missing = sorted(expected_set - observed)
    if not missing:
        return []

    gaps = _group_consecutive_dates(missing, symbol, dates[0], dates[-1], d0, d1)
    return gaps


def _group_consecutive_dates(missing, symbol, first_date, last_date, d0, d1):
    """Group a sorted list of missing dates into consecutive gap records."""
    gaps = []
    span_days = (d1 - d0).days or 1

    start = missing[0]
    end = missing[0]

    for i in range(1, len(missing)):
        if (missing[i] - missing[i - 1]).days == 1:
            end = missing[i]
        else:
            days = (end - start).days + 1
            gaps.append({
                "symbol": symbol,
                "start": str(start),
                "end": str(end),
                "days_missing": days,
                "pct": round(100 * days / span_days, 2),
            })
            start = end = missing[i]

    days = (end - start).days + 1
    gaps.append({
        "symbol": symbol,
        "start": str(start),
        "end": str(end),
        "days_missing": days,
        "pct": round(100 * days / span_days, 2),
    })

    return gaps


def check_intraday_continuity(
    df: pd.DataFrame, symbol: str, expected_interval_minutes: int = 5
) -> list[dict]:
    """
    Check intraday data for gaps > expected interval within each trading day.

    Returns list of gap records per trading day.
    """
    if df.empty:
        return []

    date_col = "date" if "date" in df.columns else None
    if date_col and date_col in df.columns:
        df = df.copy()
        df["_dt"] = pd.to_datetime(df[date_col])
    else:
        df = df.copy()
        df["_dt"] = pd.to_datetime(df.index)

    df["_day"] = df["_dt"].dt.date
    gaps = []

    for day, grp in df.groupby("_day"):
        times = sorted(grp["_dt"].dropna().unique())
        if len(times) < 2:
            continue

        for i in range(1, len(times)):
            diff = (times[i] - times[i - 1]).total_seconds() / 60
            if diff > expected_interval_minutes * 1.5:
                gaps.append({
                    "symbol": symbol,
                    "date": str(day),
                    "start": str(times[i - 1]),
                    "end": str(times[i]),
                    "gap_minutes": round(diff, 1),
                })

    return gaps


def summarize_gaps(all_gaps: dict[str, list]) -> str:
    """Generate a human-readable gap summary report."""
    if not all_gaps:
        return "No gaps detected. Data is continuous."

    lines = ["=" * 60, "DATA CONTINUITY REPORT", "=" * 60]

    total_stocks_affected = 0
    total_gaps = 0
    total_missing_days = 0

    for period, gaps in sorted(all_gaps.items()):
        if not gaps:
            continue
        total_stocks_affected += 1
        p_total_gaps = len(gaps)
        total_gaps += p_total_gaps

        lines.append(f"\n--- Period: {period} ({p_total_gaps} gaps) ---")

        # Aggregate by symbol
        by_symbol = defaultdict(list)
        for g in gaps:
            by_symbol[g["symbol"]].append(g)

        for sym, sym_gaps in sorted(by_symbol.items()):
            if "days_missing" in sym_gaps[0]:
                days = sum(g["days_missing"] for g in sym_gaps)
                total_missing_days += days
                lines.append(
                    f"  {sym}: {len(sym_gaps)} gap(s), {days} missing days total"
                )
                for g in sym_gaps[:3]:  # Show first 3
                    lines.append(
                        f"    {g['start']} ~ {g['end']}: "
                        f"{g['days_missing']} days ({g['pct']}%)"
                    )
                if len(sym_gaps) > 3:
                    lines.append(f"    ... and {len(sym_gaps) - 3} more gap(s)")
            else:
                lines.append(
                    f"  {sym}: {len(sym_gaps)} intraday gap(s)"
                )

    lines.append(f"\n{'=' * 60}")
    lines.append(
        f"Summary: {total_gaps} gaps across {total_stocks_affected} periods"
    )
    if total_missing_days:
        lines.append(f"Total missing trading days: {total_missing_days}")
    lines.append("=" * 60)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Data import
# ---------------------------------------------------------------------------

class TdxDataImporter:
    """
    Import TDX local K-line data and convert to Kronos 6-field format.

    Parameters
    ----------
    tdxdir : str, optional
        Path to TDX data directory.
    dividend_type : str
        Price adjustment type: 'front' (qfq), 'back' (hfq), or 'none'.
    start_date : str, optional
        Filter start date (YYYY-MM-DD).
    end_date : str, optional
        Filter end date (YYYY-MM-DD).
    """

    def __init__(
        self,
        tdxdir: Optional[str] = None,
        dividend_type: str = "none",
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
    ):
        self.tdxdir = tdxdir or DEFAULT_TDXDIR
        self.dividend_type = dividend_type
        self.start_date = start_date
        self.end_date = end_date
        self._reader: Optional[Reader] = None

        # Adjust type for tdxdata (qfq / hfq / None)
        self._adjust_code = ADJUST_MAP.get(dividend_type)

        # Factor cache: {code: DataFrame} persisted to disk
        self._factor_cache: dict[str, pd.DataFrame] = {}
        self._factor_cache_dir = os.path.join(
            os.path.dirname(self.tdxdir), ".factor_cache"
        )

        # Gap records: period -> list of gap dicts
        self.gaps: dict[str, list[dict]] = defaultdict(list)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def discover_stocks(self, markets=("sh", "sz", "bj")) -> list[str]:
        """Discover available stock codes from TDX daily data directory."""
        stocks = []
        for market in markets:
            lday_dir = os.path.join(self.tdxdir, "vipdoc", market, "lday")
            if not os.path.isdir(lday_dir):
                continue
            for fname in os.listdir(lday_dir):
                if fname.endswith(".day") and fname[:2] == market:
                    code = fname.replace(".day", "")
                    stocks.append(code)
        return sorted(stocks)

    def import_period(
        self,
        stock_list: list[str],
        period: str = "1d",
    ) -> pd.DataFrame:
        """
        Import a single period for multiple stocks.

        Returns DataFrame with columns:
        stock_code, date, open, high, low, close, vol, amt

        Parameters
        ----------
        stock_list : list[str]
            Stock codes like ['sh600000', 'sz000001'].
        period : str
            Target period key from PERIOD_CONFIG.
        """
        config = PERIOD_CONFIG.get(period)
        if config is None:
            raise ValueError(
                f"Unsupported period '{period}'. "
                f"Supported: {sorted(PERIOD_CONFIG.keys())}"
            )

        if config["source"] == "direct":
            return self._import_direct(stock_list, config)
        else:
            return self._import_resampled(stock_list, period, config)

    def build_dataset(
        self,
        stock_list: list[str],
        period: str = "1d",
        check_continuity: bool = True,
    ) -> dict[str, pd.DataFrame]:
        """
        Build the full {symbol: DataFrame} dataset for a period.

        Each DataFrame has datetime index and 6 Kronos columns.
        """
        print(f"\n{'=' * 60}")
        print(f"Importing period: {period}")
        print(f"Stocks: {len(stock_list)}")

        df_all = self.import_period(stock_list, period)
        if df_all.empty:
            print(f"  WARNING: No data imported for period {period}")
            return {}

        # Convert to Kronos 6-field format per symbol
        dataset = {}
        for code, grp in df_all.groupby("stock_code"):
            symbol_df = self._to_kronos_format(grp)
            if symbol_df is None or symbol_df.empty:
                continue
            dataset[code] = symbol_df

        # Continuity check
        if check_continuity and period == "1d":
            for sym, sdf in dataset.items():
                gaps = check_daily_continuity(
                    sdf, sym, self.start_date, self.end_date
                )
                if gaps:
                    self.gaps[period].extend(gaps)

            if self.gaps.get(period):
                print(f"  Found {len(self.gaps[period])} daily gap(s)")

        elif check_continuity and period in ("1m", "5m"):
            interval = 1 if period == "1m" else 5
            for sym, sdf in dataset.items():
                gaps = check_intraday_continuity(sdf, sym, interval)
                if gaps:
                    self.gaps[period].extend(gaps)

        # Print per-symbol data range summary
        if dataset:
            ranges = []
            for sym, sdf in dataset.items():
                ranges.append((sym, sdf.index[0], sdf.index[-1], len(sdf)))
            ranges.sort(key=lambda x: x[1])  # Sort by start date
            print(f"  Exported {len(dataset)} symbols")
            print(f"  Data range: {ranges[0][1].strftime('%Y-%m-%d')} ~ "
                  f"{ranges[-1][2].strftime('%Y-%m-%d')} "
                  f"(across {len(dataset)} symbols)")
        return dataset

    def save_dataset(
        self,
        dataset: dict[str, pd.DataFrame],
        output_dir: str,
        period: str = "1d",
        splits: Optional[dict[str, tuple[str, str]]] = None,
    ):
        """
        Save dataset to disk as pickle file(s).

        If splits is provided, data is split by date range and saved as
        separate files (train/val/test). Otherwise saved as single file.

        Parameters
        ----------
        dataset : dict
            {symbol: DataFrame} mapping.
        output_dir : str
            Output directory.
        period : str
            Period key, used as subdirectory name.
        splits : dict, optional
            {name: (start_date, end_date)} for train/val/test splits.
        """
        period_dir = os.path.join(output_dir, period)
        os.makedirs(period_dir, exist_ok=True)

        if splits:
            for split_name, (s_start, s_end) in splits.items():
                split_data = {}
                for sym, sdf in dataset.items():
                    mask = (sdf.index >= s_start) & (sdf.index <= s_end)
                    subset = sdf[mask]
                    if not subset.empty:
                        split_data[sym] = subset

                fpath = os.path.join(period_dir, f"{split_name}_data.pkl")
                with open(fpath, "wb") as f:
                    pickle.dump(split_data, f)
                if len(split_data) == 0:
                    print(f"  WARNING: {split_name} split is empty! "
                          f"Date range ({s_start}, {s_end}) may not overlap "
                          f"with available data. Adjust --{split_name}-range "
                          f"or remove --start-date/--end-date to import all data.")
                else:
                    print(f"  Saved {fpath} ({len(split_data)} symbols)")
        else:
            fpath = os.path.join(period_dir, "data.pkl")
            with open(fpath, "wb") as f:
                pickle.dump(dataset, f)
            print(f"  Saved {fpath} ({len(dataset)} symbols)")

    def print_gap_report(self):
        """Print the accumulated gap analysis report."""
        print(summarize_gaps(self.gaps))

    def get_gap_summary(self) -> dict:
        """Return structured gap summary for programmatic use."""
        summary = {}
        for period, gaps in self.gaps.items():
            summary[period] = {
                "total_gaps": len(gaps),
                "affected_symbols": len(set(g["symbol"] for g in gaps)),
                "details": gaps,
            }
        return summary

    # ------------------------------------------------------------------
    # Internal: data reading
    # ------------------------------------------------------------------

    def _get_reader(self) -> Reader:
        if self._reader is None:
            if not os.path.isdir(self.tdxdir):
                raise FileNotFoundError(
                    f"TDX directory not found: {self.tdxdir}. "
                    f"Specify --tdxdir or ensure default path exists."
                )
            self._reader = Reader.factory(market="std", tdxdir=self.tdxdir)
        return self._reader

    def _import_direct(
        self, stock_list: list[str], config: dict
    ) -> pd.DataFrame:
        """Import directly from TDX local files."""
        reader = self._get_reader()
        method = config["method"]
        result_parts = []

        for i, code in enumerate(stock_list):
            if (i + 1) % 200 == 0:
                print(f"  Reading... {i + 1}/{len(stock_list)}")

            try:
                df = self._fetch_single(reader, code, method)
                if df is not None and not df.empty:
                    if method == "daily" and self._adjust_code:
                        df = self._adjust_with_cache(df, code)
                    result_parts.append(df)
            except Exception as e:
                print(f"  WARNING: Failed to read {code}: {e}")

        if not result_parts:
            return pd.DataFrame()

        df_all = pd.concat(result_parts, ignore_index=True)

        # Date filtering
        if self.start_date or self.end_date:
            if "date" in df_all.columns:
                date_series = pd.to_datetime(df_all["date"], errors="coerce")
                if self.start_date:
                    df_all = df_all[date_series >= pd.Timestamp(self.start_date)]
                if self.end_date:
                    df_all = df_all[date_series <= pd.Timestamp(self.end_date)]

        return df_all

    def _import_resampled(
        self, stock_list: list[str], period: str, config: dict
    ) -> pd.DataFrame:
        """Generate period by resampling from a base period."""
        base_period = config["base"]
        rule = config["rule"]

        print(f"  Resampling from {base_period} -> {period} (rule={rule})")

        # Import base data first
        base_config = PERIOD_CONFIG[base_period]
        df_base = self._import_direct(stock_list, base_config)
        if df_base.empty:
            return pd.DataFrame()

        result_parts = []
        for code, grp in df_base.groupby("stock_code"):
            try:
                resampled = self._resample_ohlcv(grp, rule)
                if resampled is not None and not resampled.empty:
                    resampled["stock_code"] = code
                    result_parts.append(resampled)
            except Exception as e:
                print(f"  WARNING: Failed to resample {code}: {e}")

        if not result_parts:
            return pd.DataFrame()
        return pd.concat(result_parts, ignore_index=True)

    def _fetch_single(
        self, reader: Reader, code: str, method: str
    ) -> Optional[pd.DataFrame]:
        """Read a single stock from TDX local files."""
        if method == "daily":
            df = reader.daily(symbol=code)
        elif method == "minute_1":
            df = reader.minute(symbol=code, suffix=1)
        elif method == "minute_5":
            df = reader.fzline(symbol=code)
        else:
            return None

        if df is None or df.empty:
            return None

        df = df.copy()

        # Normalize index to 'date' column
        if df.index.name in ("date", "datetime"):
            df.reset_index(inplace=True)

        df["stock_code"] = code

        # Ensure date column
        if "date" not in df.columns and "datetime" in df.columns:
            df["date"] = pd.to_datetime(df["datetime"], errors="coerce")
        elif "date" in df.columns:
            df["date"] = pd.to_datetime(df["date"], errors="coerce")

        return df

    def _adjust_with_cache(
        self, df: pd.DataFrame, code: str
    ) -> pd.DataFrame:
        """Apply price adjustment with disk-cached factors."""
        if code in self._factor_cache:
            factor_df = self._factor_cache[code]
            return self._apply_factor(df, factor_df)

        cache_file = os.path.join(self._factor_cache_dir, f"{code}.pkl")
        if os.path.exists(cache_file):
            try:
                factor_df = pd.read_pickle(cache_file)
                self._factor_cache[code] = factor_df
                return self._apply_factor(df, factor_df)
            except Exception:
                pass

        try:
            df_adjusted = apply_adjust(df, code, self._adjust_code)
            from tdxdata.sources.adjust import fetch_factor
            factor_df = fetch_factor(code, self._adjust_code)
            if factor_df is not None and not factor_df.empty:
                os.makedirs(self._factor_cache_dir, exist_ok=True)
                factor_df.to_pickle(cache_file)
                self._factor_cache[code] = factor_df
            return df_adjusted
        except Exception:
            return df

    @staticmethod
    def _apply_factor(df: pd.DataFrame, factor_df: pd.DataFrame) -> pd.DataFrame:
        """Apply cached factor DataFrame to OHLC columns."""
        df = df.copy()
        date_col = "date" if "date" in df.columns else "datetime"
        if date_col not in df.columns:
            return df
        df[date_col] = pd.to_datetime(df[date_col])
        factor_df = factor_df.copy()
        factor_df.index = pd.to_datetime(factor_df.index)
        factor_df = factor_df.sort_index()
        first_val = factor_df["factor"].iloc[0]
        last_val = factor_df["factor"].iloc[-1]
        direction = "backward" if last_val > first_val else "forward"
        merged = pd.merge_asof(
            df.sort_values(date_col).reset_index(drop=True),
            factor_df[["factor"]],
            left_on=date_col,
            right_index=True,
            direction=direction,
        )
        merged["factor"] = merged["factor"].ffill().bfill().fillna(1.0)
        for col in ["open", "high", "low", "close"]:
            if col in merged.columns:
                merged[col] = merged[col] * merged["factor"]
        merged = merged.drop(columns=["factor"], errors="ignore")
        return merged

    # ------------------------------------------------------------------
    # Internal: resampling
    # ------------------------------------------------------------------

    @staticmethod
    def _resample_ohlcv(df: pd.DataFrame, rule: str) -> Optional[pd.DataFrame]:
        """Resample OHLCV data to a new frequency."""
        df = df.copy()
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
        df = df.set_index("date").sort_index()

        # Ensure numeric types
        for col in ["open", "high", "low", "close"]:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        for col in ["volume", "amount"]:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

        # Only resample rows that have OHLC
        ohlc_cols = [c for c in ["open", "high", "low", "close"] if c in df.columns]
        if len(ohlc_cols) < 4:
            return None

        valid_mask = df[ohlc_cols].notna().all(axis=1)
        if not valid_mask.any():
            return None

        resampled = df[valid_mask].resample(rule).agg(OHLCV_AGG)

        # Remove rows with all-NaN OHLC
        resampled = resampled.dropna(subset=ohlc_cols, how="all")
        resampled = resampled.reset_index()

        return resampled

    # ------------------------------------------------------------------
    # Internal: format conversion
    # ------------------------------------------------------------------

    def _to_kronos_format(self, df: pd.DataFrame) -> Optional[pd.DataFrame]:
        """
        Convert a single-stock TDX DataFrame to Kronos 6-field format.

        Returns DataFrame with datetime index and columns:
        open, high, low, close, vol, amt
        """
        df = df.copy()

        # Date handling
        if "date" in df.columns:
            df["date"] = pd.to_datetime(df["date"], errors="coerce")
            df = df.dropna(subset=["date"])
            df = df.set_index("date")
        elif df.index.name in ("date", "datetime"):
            df.index = pd.to_datetime(df.index, errors="coerce")

        df = df.sort_index()

        # Normalize column names
        # Map TDX names to Kronos names
        rename = {}
        for col in df.columns:
            if col in ("open", "high", "low", "close"):
                pass  # Keep as-is
            elif col == "volume":
                rename["volume"] = "vol"
            elif col == "amount":
                rename["amount"] = "amt"
            elif col in ("vol", "amt"):
                pass

        df = df.rename(columns=rename)

        # Ensure numeric types
        for col in ["open", "high", "low", "close"]:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")

        if "vol" in df.columns:
            df["vol"] = pd.to_numeric(df["vol"], errors="coerce").fillna(0)
        if "amt" in df.columns:
            df["amt"] = pd.to_numeric(df["amt"], errors="coerce").fillna(0)

        # Compute amount if missing or all-zero
        need_amt = True
        if "amt" in df.columns:
            if df["amt"].notna().any() and (df["amt"] > 0).any():
                need_amt = False

        if need_amt:
            ohlc_cols = ["open", "high", "low", "close"]
            if all(c in df.columns for c in ohlc_cols) and "vol" in df.columns:
                mean_ohlc = df[ohlc_cols].mean(axis=1)
                df["amt"] = mean_ohlc * df["vol"]
            else:
                df["amt"] = 0.0

        # Keep only Kronos 6 columns
        keep = [c for c in FEATURE_COLUMNS if c in df.columns]
        df = df[keep]

        # Drop rows where all OHLC are NaN
        ohlc = [c for c in ["open", "high", "low", "close"] if c in df.columns]
        if ohlc:
            df = df.dropna(subset=ohlc, how="all")

        if df.empty:
            return None

        return df


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(
        description="TDX local data import tool for Kronos fine-tuning"
    )

    p.add_argument(
        "--tdxdir",
        default=DEFAULT_TDXDIR,
        help=f"TDX data directory (default: {DEFAULT_TDXDIR})",
    )
    p.add_argument(
        "--symbols",
        nargs="*",
        help="Stock codes to import (e.g. sh600000 sz000001). "
             "If omitted, auto-discover all stocks.",
    )
    p.add_argument(
        "--symbol-file",
        help="File with stock codes, one per line",
    )
    p.add_argument(
        "--periods",
        nargs="+",
        default=["1d"],
        choices=list(PERIOD_CONFIG.keys()),
        help="Periods to import (default: 1d)",
    )
    p.add_argument(
        "--dividend-type",
        default="none",
        choices=["none", "front", "back"],
        help="Price adjustment type: front (qfq), back (hfq), none (default)",
    )
    p.add_argument(
        "--output-dir",
        default="./data/tdx_import",
        help="Output directory (default: ./data/tdx_import)",
    )
    p.add_argument(
        "--start-date",
        help="Start date filter (YYYY-MM-DD)",
    )
    p.add_argument(
        "--end-date",
        help="End date filter (YYYY-MM-DD)",
    )
    p.add_argument(
        "--no-split",
        action="store_true",
        help="Save as single file instead of train/val/test splits",
    )
    p.add_argument(
        "--train-range",
        nargs=2,
        default=["2011-01-01", "2022-12-31"],
        metavar=("START", "END"),
        help="Training set date range (default: 2011-01-01 2022-12-31)",
    )
    p.add_argument(
        "--val-range",
        nargs=2,
        default=["2022-09-01", "2024-06-30"],
        metavar=("START", "END"),
        help="Validation set date range (default: 2022-09-01 2024-06-30)",
    )
    p.add_argument(
        "--test-range",
        nargs=2,
        default=["2024-04-01", "2025-06-05"],
        metavar=("START", "END"),
        help="Test set date range (default: 2024-04-01 2025-06-05)",
    )
    p.add_argument(
        "--no-continuity",
        action="store_true",
        help="Skip data continuity check",
    )
    p.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Limit to first N stocks (for testing, 0 = all)",
    )
    p.add_argument(
        "--list-stocks",
        action="store_true",
        help="List available stocks and exit",
    )

    return p.parse_args()


def load_symbols(args) -> list[str]:
    """Resolve stock list from CLI args."""
    if args.symbols:
        return args.symbols

    if args.symbol_file:
        with open(args.symbol_file) as f:
            return [line.strip() for line in f if line.strip()]

    # Auto-discover
    importer = TdxDataImporter(tdxdir=args.tdxdir)
    stocks = importer.discover_stocks()
    print(f"Auto-discovered {len(stocks)} stocks")
    return stocks


def main():
    args = parse_args()

    # List stocks mode
    if args.list_stocks:
        importer = TdxDataImporter(tdxdir=args.tdxdir)
        stocks = importer.discover_stocks()
        print(f"Found {len(stocks)} stocks:")
        for s in stocks:
            print(f"  {s}")
        return

    # Load symbols
    stock_list = load_symbols(args)
    if not stock_list:
        print("ERROR: No stocks specified or discovered.")
        sys.exit(1)

    if args.limit > 0:
        stock_list = stock_list[: args.limit]
        print(f"Limited to first {args.limit} stocks")

    # Configure splits
    splits = None
    if not args.no_split:
        splits = {
            "train": tuple(args.train_range),
            "val": tuple(args.val_range),
            "test": tuple(args.test_range),
        }

    # Run import
    importer = TdxDataImporter(
        tdxdir=args.tdxdir,
        dividend_type=args.dividend_type,
        start_date=args.start_date,
        end_date=args.end_date,
    )

    for period in args.periods:
        dataset = importer.build_dataset(
            stock_list=stock_list,
            period=period,
            check_continuity=not args.no_continuity,
        )

        if not dataset:
            print(f"  SKIP: No data for period {period}")
            continue

        importer.save_dataset(
            dataset=dataset,
            output_dir=args.output_dir,
            period=period,
            splits=splits,
        )

    # Continuity report
    if not args.no_continuity:
        importer.print_gap_report()

    print(f"\nDone. Output saved to {args.output_dir}/")
    print("To use with Kronos, update finetune/config.py:")
    print(f"  self.dataset_path = \"{os.path.abspath(args.output_dir)}/1d\"")


if __name__ == "__main__":
    main()
